import { TopikPaper, Textbook } from './types';

// ==========================================
// KOREAN HUB CONFIGURATION & DATA SOURCE
// Easily swap in your actual smartlink and download URLs below.
// ==========================================

export const AD_SMARTLINK = "https://www.profitableratecpmnetwork.com/c9d12u9g8?key=1b41720a35a51bbfe4d7666de867f4cb";

export const topikPapers: TopikPaper[] = [
  {
    id: 'topik-102-1',
    session: '102nd TOPIK I Exam',
    level: 'TOPIK I',
    year: '2025',
    date: '2025 Official Exam',
    downloadsCount: 3450,
    questionPdfUrl: 'https://files.topikguide.com/test-papers/102nd-TOPIK-I-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://files.topikguide.com/test-papers/102nd-TOPIK-I-Reading-Answers.pdf',
    audioUrl: 'https://files.topikguide.com/listening/102-TOPIK-I-Listening-Audio-File.mp3',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-I-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-I-Listening-Test-Paper.pdf' },
      { title: 'Reading Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-I-Reading-Answers.pdf' },
      { title: 'Listening Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-I-Listening-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-I-Listening-Transcript.pdf' },
      { title: 'Listening Audio (.mp3)', type: 'audio', url: 'https://files.topikguide.com/listening/102-TOPIK-I-Listening-Audio-File.mp3' }
    ]
  },
  {
    id: 'topik-102-2',
    session: '102nd TOPIK II Exam',
    level: 'TOPIK II',
    year: '2025',
    date: '2025 Official Exam',
    downloadsCount: 4210,
    questionPdfUrl: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Reading-Answers.pdf',
    audioUrl: 'https://files.topikguide.com/listening/102-TOPIK-II-Listening-Audio-File.mp3',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Listening-Test-Paper.pdf' },
      { title: 'Writing Test (PDF)', type: 'writing', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Writing-Test-Paper.pdf' },
      { title: 'Reading Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Reading-Answers.pdf' },
      { title: 'Listening Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Listening-Answers.pdf' },
      { title: 'Writing Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Writing-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://files.topikguide.com/test-papers/102nd-TOPIK-II-Listening-Transcript.pdf' },
      { title: 'Listening Audio (.mp3)', type: 'audio', url: 'https://files.topikguide.com/listening/102-TOPIK-II-Listening-Audio-File.mp3' }
    ]
  },
  {
    id: 'topik-96-1',
    session: '96th TOPIK I Exam',
    level: 'TOPIK I',
    year: '2025',
    date: '2025 Official Exam',
    downloadsCount: 2980,
    questionPdfUrl: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-I-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-I-Answers.pdf',
    audioUrl: 'https://drive.google.com/file/d/1vBC0RgjRiJfdFRblPPP6txxz7mG_1Ba0/view',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-I-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-I-Listening-Test-Paper.pdf' },
      { title: 'Answer Keys (PDF)', type: 'answer', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-I-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-I-Listening-Transcript.pdf' },
      { title: 'Listening Audio', type: 'audio', url: 'https://drive.google.com/file/d/1vBC0RgjRiJfdFRblPPP6txxz7mG_1Ba0/view' }
    ]
  },
  {
    id: 'topik-96-2',
    session: '96th TOPIK II Exam',
    level: 'TOPIK II',
    year: '2025',
    date: '2025 Official Exam',
    downloadsCount: 3640,
    questionPdfUrl: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-II-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-II-Answers.pdf',
    audioUrl: 'https://drive.google.com/file/d/1ebLFch7tPAjzZ59jJR_ndGcmWJCCEmby/view',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-II-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-II-Listening-Test-Paper.pdf' },
      { title: 'Writing Test (PDF)', type: 'writing', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-II-Writing-Test-Paper.pdf' },
      { title: 'Answer Keys (PDF)', type: 'answer', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-II-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://www.topikguide.com/TOPIK-Papers/96th-TOPIK-II-Listening-Transcript.pdf' },
      { title: 'Listening Audio', type: 'audio', url: 'https://drive.google.com/file/d/1ebLFch7tPAjzZ59jJR_ndGcmWJCCEmby/view' }
    ]
  },
  {
    id: 'topik-91-1',
    session: '91st TOPIK I Exam',
    level: 'TOPIK I',
    year: '2024',
    date: '2024 Official Exam',
    downloadsCount: 3120,
    questionPdfUrl: 'https://files.topikguide.com/test-papers/91st-TOPIK-I-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://files.topikguide.com/test-papers/91st-TOPIK-I-Reading-Answers.pdf',
    audioUrl: 'https://files.topikguide.com/listening/91-TOPIK-I-Listening-Audio-File.mp3',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-I-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-I-Listening-Test-Paper.pdf' },
      { title: 'Reading Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-I-Reading-Answers.pdf' },
      { title: 'Listening Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-I-Listening-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-I-Listening-Transcript.pdf' },
      { title: 'Listening Audio (.mp3)', type: 'audio', url: 'https://files.topikguide.com/listening/91-TOPIK-I-Listening-Audio-File.mp3' }
    ]
  },
  {
    id: 'topik-91-2',
    session: '91st TOPIK II Exam',
    level: 'TOPIK II',
    year: '2024',
    date: '2024 Official Exam',
    downloadsCount: 3890,
    questionPdfUrl: 'https://files.topikguide.com/test-papers/91st-TOPIK-II-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://files.topikguide.com/test-papers/91st-TOPIK-II-Reading-Answers.pdf',
    audioUrl: 'https://files.topikguide.com/listening/91-TOPIK-II-Listening-Audio-File.mp3',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-II-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-II-Listening-Test-Paper.pdf' },
      { title: 'Writing Test (PDF)', type: 'writing', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-II-Writing-Test-Paper.pdf' },
      { title: 'Reading Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-II-Reading-Answers.pdf' },
      { title: 'Listening Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-II-Listening-Answers.pdf' },
      { title: 'Writing Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/91st-TOPIK-II-Writing-Answers.pdf' },
      { title: 'Listening Audio (.mp3)', type: 'audio', url: 'https://files.topikguide.com/listening/91-TOPIK-II-Listening-Audio-File.mp3' }
    ]
  },

  {
    id: 'topik-83-1',
    session: '83rd TOPIK I Exam',
    level: 'TOPIK I',
    year: '2023',
    date: '2023 Official Exam',
    downloadsCount: 2650,
    questionPdfUrl: 'https://files.topikguide.com/test-papers/83rd-TOPIK-I-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://files.topikguide.com/test-papers/83rd-TOPIK-I-Reading-Answers.pdf',
    audioUrl: 'https://files.topikguide.com/listening/83-TOPIK-I-Listening-Audio-File.mp3',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-I-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-I-Listening-Test-Paper.pdf' },
      { title: 'Reading Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-I-Reading-Answers.pdf' },
      { title: 'Listening Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-I-Listening-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-I-Listening-Transcript.pdf' },
      { title: 'Listening Audio (.mp3)', type: 'audio', url: 'https://files.topikguide.com/listening/83-TOPIK-I-Listening-Audio-File.mp3' }
    ]
  },
  {
    id: 'topik-83-2',
    session: '83rd TOPIK II Exam',
    level: 'TOPIK II',
    year: '2023',
    date: '2023 Official Exam',
    downloadsCount: 3120,
    questionPdfUrl: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Reading-Answers.pdf',
    audioUrl: 'https://files.topikguide.com/listening/83-TOPIK-II-Listening-Audio-File.mp3',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Listening-Test-Paper.pdf' },
      { title: 'Writing Test (PDF)', type: 'writing', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Writing-Test-Paper.pdf' },
      { title: 'Reading Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Reading-Answers.pdf' },
      { title: 'Listening Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Listening-Answers.pdf' },
      { title: 'Writing Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Writing-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://files.topikguide.com/test-papers/83rd-TOPIK-II-Listening-Transcript.pdf' },
      { title: 'Listening Audio (.mp3)', type: 'audio', url: 'https://files.topikguide.com/listening/83-TOPIK-II-Listening-Audio-File.mp3' }
    ]
  },

  {
    id: 'topik-64-1',
    session: '64th TOPIK I Exam',
    level: 'TOPIK I',
    year: '2019',
    date: '2019 Official Exam',
    downloadsCount: 4230,
    questionPdfUrl: 'https://files.topikguide.com/test-papers/64th-TOPIK-I-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://files.topikguide.com/test-papers/64th-TOPIK-I-Reading-Answers.pdf',
    audioUrl: 'https://files.topikguide.com/listening/64-TOPIK-I-Listening-Audio-File.mp3',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-I-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-I-Listening-Test-Paper.pdf' },
      { title: 'Reading Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-I-Reading-Answers.pdf' },
      { title: 'Listening Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-I-Listening-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-I-Listening-Transcript.pdf' },
      { title: 'Listening Audio (.mp3)', type: 'audio', url: 'https://files.topikguide.com/listening/64-TOPIK-I-Listening-Audio-File.mp3' }
    ]
  },
  {
    id: 'topik-64-2',
    session: '64th TOPIK II Exam',
    level: 'TOPIK II',
    year: '2019',
    date: '2019 Official Exam',
    downloadsCount: 5430,
    questionPdfUrl: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Reading-Test-Paper.pdf',
    answerPdfUrl: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Reading-Answers.pdf',
    audioUrl: 'https://files.topikguide.com/listening/64-TOPIK-II-Listening-Audio-File.mp3',
    files: [
      { title: 'Reading Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Reading-Test-Paper.pdf' },
      { title: 'Listening Test (PDF)', type: 'question', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Listening-Test-Paper.pdf' },
      { title: 'Writing Test (PDF)', type: 'writing', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Writing-Test-Paper.pdf' },
      { title: 'Reading Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Reading-Answers.pdf' },
      { title: 'Listening Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Listening-Answers.pdf' },
      { title: 'Writing Answers (PDF)', type: 'answer', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Writing-Answers.pdf' },
      { title: 'Listening Transcript (PDF)', type: 'transcript', url: 'https://files.topikguide.com/test-papers/64th-TOPIK-II-Listening-Transcript.pdf' },
      { title: 'Listening Audio (.mp3)', type: 'audio', url: 'https://files.topikguide.com/listening/64-TOPIK-II-Listening-Audio-File.mp3' }
    ]
  },
  {
    id: 'topik-60',
    session: '60th TOPIK Exam',
    level: 'Both',
    year: '2018',
    date: 'October 2018',
    downloadsCount: 4100,
    questionPdfUrl: '#',
    answerPdfUrl: '#',
    isComingSoon: true,
  },
  {
    id: 'topik-52',
    session: '52nd TOPIK Exam',
    level: 'Both',
    year: '2017',
    date: 'July 2017',
    downloadsCount: 3890,
    questionPdfUrl: '#',
    answerPdfUrl: '#',
    isComingSoon: true,
  },
  {
    id: 'topik-47',
    session: '47th TOPIK Exam',
    level: 'Both',
    year: '2016',
    date: 'July 2016',
    downloadsCount: 2450,
    questionPdfUrl: '#',
    answerPdfUrl: '#',
    isComingSoon: true,
  },
  {
    id: 'topik-41',
    session: '41st TOPIK Exam',
    level: 'Both',
    year: '2015',
    date: 'July 2015',
    downloadsCount: 2120,
    questionPdfUrl: '#',
    answerPdfUrl: '#',
    isComingSoon: true,
  },
  {
    id: 'topik-37',
    session: '37th TOPIK Exam',
    level: 'Both',
    year: '2014',
    date: 'October 2014',
    downloadsCount: 1980,
    questionPdfUrl: '#',
    answerPdfUrl: '#',
    isComingSoon: true,
  },
  {
    id: 'topik-36',
    session: '36th TOPIK Exam',
    level: 'Both',
    year: '2014',
    date: 'July 2014',
    downloadsCount: 1850,
    questionPdfUrl: '#',
    answerPdfUrl: '#',
    isComingSoon: true,
  },
  {
    id: 'topik-35',
    session: '35th TOPIK Exam',
    level: 'Both',
    year: '2014',
    date: 'July 2014',
    downloadsCount: 2300,
    questionPdfUrl: '#',
    answerPdfUrl: '#',
    isComingSoon: true,
  }
];

export const textbooks: Textbook[] = [
  {
    id: 'tb-1',
    title: 'MAGIC KOREAN: Mastering Korean for Beginners in 31 days',
    level: 'Level 1 (Beginner)',
    category: 'Textbook & MP3',
    description: 'Mastering Korean for Beginners in 31 days (매직 코리안 1) by Kwack Sangheun. Complete beginner guide with systematic daily lessons and free MP3 audio.',
    pages: '310 pages + Free MP3',
    downloadsCount: 15420,
    downloadUrl: 'https://welib.org/auto_download/d83bf3411f83f1f044766ee44f7e2134/0/0',
    coverStyle: 'yellow',
  },
  {
    id: 'tb-2',
    title: 'Korean: A Comprehensive Grammar',
    level: 'Level 1 (Beginner)',
    category: 'Routledge Grammar',
    description: 'Korean: A Comprehensive Grammar by Jaehoon Yeon and Lucien Brown. The definitive reference guide to Korean grammar structures.',
    pages: '450 pages',
    downloadsCount: 14890,
    downloadUrl: 'https://welib.org/slow_download/3466b38bd8382145b0fab543421ccb2d/0/0/convert',
    coverStyle: 'routledge',
  },
  {
    id: 'tb-3',
    title: 'Korean Made Simple: A beginner’s guide to learning the Korean language',
    level: 'Level 1 (Beginner)',
    category: 'Beginner Guide',
    description: 'Korean Made Simple by Billy Go. A beginner’s guide to learning the Korean language with easy explanations and illustrations.',
    pages: '312 pages',
    downloadsCount: 16800,
    downloadUrl: 'https://welib.org/slow_download/b3d7bf79fbd73dc5a9728eba038a2b2f/0/0/convert',
    coverImageUrl: 'https://i.postimg.cc/ydPPv17R/proxy-(2).jpg',
    coverStyle: 'billygo',
  },
  {
    id: 'tb-4',
    title: 'Korean Made Simple 2: The next step in learning the Korean language',
    level: 'Level 2 (Elementary)',
    category: 'Beginner Guide',
    description: 'Korean Made Simple 2 by Billy Go. The next step in learning the Korean language with continued grammar and vocabulary.',
    pages: '340 pages',
    downloadsCount: 14200,
    downloadUrl: 'https://welib.org/slow_download/968b7fa902b6e5b1d8074c487cec4387/0/0/convert',
    coverImageUrl: 'https://i.postimg.cc/yYNfpZgZ/proxy-(3).jpg',
    coverStyle: 'billygo2',
  },
  {
    id: 'tb-5',
    title: 'Korean Made Simple 3: Continuing your journey of learning the Korean language',
    level: 'Level 3 (Intermediate)',
    category: 'Intermediate Guide',
    description: 'Korean Made Simple 3 by Billy Go. Continuing your journey of learning the Korean language with advanced beginner and intermediate grammar points.',
    pages: '372 pages',
    downloadsCount: 12500,
    downloadUrl: 'https://welib.org/fast_download/5cf67f1a52ffdb63878572dd3e6b8310/0/0/convert',
    coverImageUrl: 'https://i.postimg.cc/pdjcYM9B/proxy-(4).jpg',
    coverStyle: 'billygo3',
  },
  {
    id: 'tb-6',
    title: 'Korean grammar in use : beginning to early intermediate',
    level: 'Level 1 (Beginner)',
    category: 'Grammar',
    description: 'Korean grammar in use: beginning to early intermediate. Essential grammar points for beginners and early intermediate learners.',
    pages: '380 pages',
    downloadsCount: 11200,
    downloadUrl: 'https://welib.org/slow_download/57de504ac358346a76d642be275c6514/0/0',
    coverImageUrl: 'https://i.postimg.cc/cJsRbqCD/proxy-(5).jpg',
    coverStyle: 'rose',
  },
  {
    id: 'tb-7',
    title: 'Korean Grammar in Use : Intermediate (Korean edition) by Min Jin-young',
    level: 'Level 3 (Intermediate)',
    category: 'Grammar',
    description: 'Korean Grammar in Use: Intermediate (Korean edition) by Min Jin-young. Master intermediate nuance and grammar structures.',
    pages: '412 pages',
    downloadsCount: 9400,
    downloadUrl: 'https://welib.org/slow_download/4ddf767822f7501a89a502619064b0d7/0/0',
    coverStyle: 'sage',
  },
  {
    id: 'tb-8',
    title: 'Talk To Me In Korean Level 1 (English and Korean Edition) 1',
    level: 'Level 1 (Beginner)',
    category: 'TTMIK',
    description: 'Talk To Me In Korean Level 1 (English and Korean Edition). Natural, conversational Korean for absolute beginners.',
    pages: '230 pages + Audio',
    downloadsCount: 21500,
    downloadUrl: 'https://welib.org/slow_download/a29cd481f7626fae45ede43b3097bffa/0/0',
    coverImageUrl: 'https://i.postimg.cc/Vv39Gd04/proxy-(6).jpg',
    coverStyle: 'lavender',
  },
  {
    id: 'tb-9',
    title: 'Talk to Me in Korean Level 2 Korean Grammar Textbook',
    level: 'Level 2 (Elementary)',
    category: 'TTMIK',
    description: 'Talk to Me in Korean Level 2 Korean Grammar Textbook. Build on your foundational skills with natural dialogues and clear explanations.',
    pages: '250 pages + Audio',
    downloadsCount: 18400,
    downloadUrl: 'https://welib.org/slow_download/ad245b62d2bff1e03219607531632b44/0/0',
    coverImageUrl: 'https://i.postimg.cc/HkTzf8P2/proxy-(13).jpg',
    coverStyle: 'amber',
  },
  {
    id: 'tb-10',
    title: 'Talk to Me in Korean Level 3 Korean Grammar Textbook',
    level: 'Level 3 (Intermediate)',
    category: 'TTMIK',
    description: 'Talk to Me in Korean Level 3. Expand your grammar and vocabulary with intermediate natural dialogues and lessons.',
    pages: '270 pages + Audio',
    downloadsCount: 15300,
    downloadUrl: 'https://welib.org/slow_download/5e65af037f60508e28d4e7a510f5667d/0/0',
    coverImageUrl: 'https://i.postimg.cc/NjRDn74F/proxy-(8).jpg',
    coverStyle: 'sky',
  },
  {
    id: 'tb-11',
    title: 'TOPIK - The Self-Study Guide [For All Levels]',
    level: 'All Levels',
    category: 'TOPIK Prep',
    description: 'Comprehensive self-study guide for the TOPIK exam covering all levels with tips, strategies, and practice.',
    pages: '340 pages',
    downloadsCount: 19800,
    downloadUrl: 'https://welib.org/slow_download/b783216a76f02dc4e4457e576d017acf/0/0/convert',
    coverImageUrl: 'https://i.postimg.cc/4NSjG5p4/proxy-(12).jpg',
    coverStyle: 'routledge',
  },
  {
    id: 'tb-12',
    title: 'Complete Guide to the TOPIK II- New Edition (Intermediate - Advanced) 2',
    level: 'Level 4 (Advanced)',
    category: 'TOPIK Prep',
    description: 'Complete Guide to the TOPIK II New Edition. Essential preparation for intermediate and advanced TOPIK test takers.',
    pages: '450 pages + Practice',
    downloadsCount: 11400,
    downloadUrl: 'https://welib.org/slow_download/3434c2b69a688239881c11c5c69207c9/0/0',
    coverImageUrl: 'https://i.postimg.cc/BZhV5gY5/proxy-(11).jpg',
    coverStyle: 'rose',
  },
  {
    id: 'tb-13',
    title: 'Complete Guide to the TOPIK I- New Edition (Basic) 1',
    level: 'Level 1 (Beginner)',
    category: 'TOPIK Prep',
    description: 'Complete Guide to the TOPIK I New Edition. Basic level reading and listening preparation for beginners.',
    pages: '290 pages + Practice',
    downloadsCount: 23100,
    downloadUrl: 'https://welib.org/slow_download/47c9c5bf0ca1b9bc1e86bad6467d7655/0/0',
    coverImageUrl: 'https://i.postimg.cc/yd1Lcg0p/proxy-(9).jpg',
    coverStyle: 'yellow',
  },
  {
    id: 'tb-14',
    title: 'SEJONG KOREAN ENGLISH EDITION 1A (세종 한국어 1A)',
    level: 'Level 1 (Beginner)',
    category: 'Sejong Institute',
    description: 'SEJONG KOREAN ENGLISH EDITION 1A by King Sejong Institute and National Institute of Korean Language. Official beginner textbook with extension activities.',
    pages: '280 pages + Audio',
    downloadsCount: 25400,
    downloadUrl: 'https://drive.google.com/file/d/1sPVFDU81sfwpmiNsvo7De-aNRjPBDNtU/view?usp=sharing',
    coverImageUrl: 'https://i.postimg.cc/VLj2QyRZ/9781635190472.jpg',
    coverStyle: 'sage',
    tag: 'NEW RELEASE',
  },
  {
    id: 'tb-15',
    title: 'SEJONG KOREAN ENGLISH EDITION 1B (세종 한국어 1B)',
    level: 'Level 1 (Beginner)',
    category: 'Sejong Institute',
    description: 'SEJONG KOREAN ENGLISH EDITION 1B by King Sejong Institute and National Institute of Korean Language. Official beginner textbook continuation.',
    pages: '272 pages + Audio',
    downloadsCount: 19800,
    downloadUrl: 'https://drive.google.com/file/d/16BP0uh0rHWptgaVQh0ZEcHlaMSiUIfBm/view?usp=sharing',
    coverImageUrl: 'https://i.postimg.cc/VLj2QyRZ/9781635190472.jpg',
    coverStyle: 'amber',
    tag: 'NEW RELEASE',
  },
  {
    id: 'tb-16',
    title: 'SEJONG KOREAN ENGLISH EDITION 2A (세종 한국어 2A)',
    level: 'Level 2 (Elementary)',
    category: 'Sejong Institute',
    description: 'SEJONG KOREAN ENGLISH EDITION 2A by King Sejong Institute. Elementary curriculum with vocabulary and conversational practice.',
    pages: '296 pages + Audio',
    downloadsCount: 17200,
    downloadUrl: 'https://drive.google.com/file/d/1ShEIU05QvVLBWhIqUUgwg6NOK6q4LP0N/view?usp=sharing',
    coverImageUrl: 'https://i.postimg.cc/VLj2QyRZ/9781635190472.jpg',
    coverStyle: 'sky',
    tag: 'NEW RELEASE',
  },
  {
    id: 'tb-17',
    title: 'SEJONG KOREAN ENGLISH EDITION 2B (세종 한국어 2B)',
    level: 'Level 2 (Elementary)',
    category: 'Sejong Institute',
    description: 'SEJONG KOREAN ENGLISH EDITION 2B by King Sejong Institute. Continuing elementary curriculum with dialogue and listening exercises.',
    pages: '310 pages + Audio',
    downloadsCount: 15900,
    downloadUrl: 'https://drive.google.com/file/d/1yDMRRf_5A39IA2cOU2DeK24IDaXgxJe0/view?usp=sharing',
    coverImageUrl: 'https://i.postimg.cc/VLj2QyRZ/9781635190472.jpg',
    coverStyle: 'lavender',
    tag: 'NEW RELEASE',
  }
];
